### PR TITLE
Split code into multiple files

### PR DESCRIPTION
**Pull request by tugorez**
Files are split using the following convention:

- The `screens/` folder contains "screens" or "pages" that should match 1:1 with routes
- The `components/ ` folder contains "widget primitives" used by the screens.
- When needed we can also `utils` or `infra` folders.

In addition to splitting, took the time to refactor the text editor widget component in hopefully, a positive, way.

### CODE REVIEW

**Comment by tugorez** [comment]
FYI I'll prolly follow up with some tests and functionality to inspect the data and user triggered events.

**Comment by johnmccutchan** [comment]
This is LGTM but you need to mark the new files as branched from the original lib/main.dart so that we can track version history correctly.

**Comment by tugorez** [comment]
Apologize in advance for the noob question (its been a few years since I used git): 
Do you have any idea of this can be achieved? Did a quick research but found nothing to do something like this.

**Comment by johnmccutchan** [comment]
git mv can work but it might not be worth it at this point

**Pull request merged**
